"""Added chatbot relationship to Message model

Revision ID: 071062cde02d
Revises: 3b92d69d8b4b
Create Date: 2024-12-11 09:51:31.304324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '071062cde02d'
down_revision = '3b92d69d8b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_id', sa.Integer(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('messages_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_chat_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chatbots', ['chatbot_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('response')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_chat_id_fkey', 'chatbots', ['chat_id'], ['id'])
        batch_op.create_foreign_key('messages_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('chatbot_id')

    # ### end Alembic commands ###
