"""Updated models with relationships

Revision ID: 0c1caea42890
Revises: aee854fd8343
Create Date: 2024-12-12 02:17:53.767479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1caea42890'
down_revision = 'aee854fd8343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('chatbot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('chatbot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
