"""Initial migratiokk

Revision ID: 0efc32f5cc91
Revises: 9faea47c98db
Create Date: 2024-12-11 15:18:47.948462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0efc32f5cc91'
down_revision = '9faea47c98db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('agents_chatbot_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('agents_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('chatbot_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_column('script_code')
        batch_op.drop_column('website_url')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ip', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('response', sa.Text(), nullable=False))
        batch_op.alter_column('chatbot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('messages_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('content')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('messages_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('chatbot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('response')
        batch_op.drop_column('message')
        batch_op.drop_column('user_ip')

    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('script_code', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('agents_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('agents_chatbot_id_fkey', 'chatbots', ['chatbot_id'], ['id'])

    # ### end Alembic commands ###
