"""Added foreign key relationship between Agent and Chatbot

Revision ID: 3b92d69d8b4b
Revises: e6c06b6fd182
Create Date: 2024-12-11 09:47:33.560331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b92d69d8b4b'
down_revision = 'e6c06b6fd182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chatbots', ['chatbot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chatbot_id')

    # ### end Alembic commands ###
