"""Updated models with relationships

Revision ID: 7824d4505b13
Revises: 1a68d062ec4c
Create Date: 2024-12-11 23:25:29.841413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7824d4505b13'
down_revision = '1a68d062ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
