"""okokooo

Revision ID: 8ae999fa553f
Revises: 43731f2dd360
Create Date: 2024-12-11 10:08:50.210722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae999fa553f'
down_revision = '43731f2dd360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('chatbot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('chatbot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
