"""update

Revision ID: 9faea47c98db
Revises: 8ae999fa553f
Create Date: 2024-12-11 10:22:04.540276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9faea47c98db'
down_revision = '8ae999fa553f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('prompt')
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
