"""Updated models with relationships

Revision ID: bc2280de5907
Revises: 0c1caea42890
Create Date: 2024-12-12 06:00:50.705706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2280de5907'
down_revision = '0c1caea42890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
